### ISSUE TITLE
NPM docs have a typo

### ISSUE THREAD

**Issue by aBitNomadic** [ptitdam2001/ng2-weather-icons#6]
the text for the angular cli has you add
        "../node_modules/weather-icons/css/weather-icons-winds.css"
to the angular-cli.json when it should be
        "../node_modules/weather-icons/css/weather-icons-wind.css"

**Comment by mikail1998** [comment]
@aBitNomadic i was about to open the same issue ahahhah

**Comment by ptitdam2001** [comment]
I will update the documentation
