### ISSUE TITLE
Compiling from angular -cli 

### ISSUE THREAD

**Issue by mikailbayram** [ptitdam2001/ng2-weather-icons#7]
i get this error in my terminal 
ERROR in default is not an NgModule
webpack: Failed to compile.

I hope to solve this problem as soon as possible

**Comment by kirtiesl** [comment]
Hello I am getting the same issue. Please help!!

**Comment by mikail1998** [comment]
It was a long time ago, Im sorry but I really dont remember how i solved the issue

**Comment by ptitdam2001** [comment]
Which version of angular-cli are you using?

**Comment by kirtiesl** [comment]
Hi,
I am using angular-cli: 1.0.0-beta.28.3

**Comment by kirtiesl** [comment]
Please suggest solution. It's urgent

**Comment by ptitdam2001** [comment]
I am on the problem.

the only solution you can do it is to copy the source code into your project.
It is only one component and pipe

**Comment by ptitdam2001** [comment]
Another solution downgrade your typescript version (https://fluin.io/blog/appmodule-is-not-an-ngmodule)

**Comment by kirtiesl** [comment]
My typescript version is 2.0.10, still its not working
